
# Isolated Test Database
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_TEST_NAME:veritasvault_test}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345678}
spring.datasource.driver-class-name=org.postgresql.Driver

# Clean database state on every test execution
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Test JWT Key (Fast expiration)
app.jwt.secret=TestSecretKeyNeedToBeAtLeast256BitsLongForHS256AlgorithmTestingPurposesOnly
app.jwt.expiration-ms=3600000

# Mock Mail Port (Prevents tests from attempting to send actual emails)
spring.mail.host=localhost
spring.mail.port=2525